import numpy as np

DETECTOR_SIZE = 2.0
DETECTOR_POSITIONS = [(x * 0.5 - 1.25, y * 0.5 - 1.25, z * 0.5 - 0.5) for x in range(6) for y in range(6) for z in range(3)]

GENERATOR_POSITION = (0, 0, 0)
GENERATOR_MODE = 'pulse'

GENERATOR_PULSE_DISTRIBUTION = 'gaussian'
GENERATOR_PULSE_MEAN = 0
GENERATOR_PULSE_STD = 2.0
GENERATOR_PULSE_UNIFORM_MIN = -2
GENERATOR_PULSE_UNIFORM_MAX = 2

MIN_TRACK_LENGTH = 0.001
SIMULATION_TIME = 50
PARTICLE_SPEED = 1.0
TRAJECTORY_SPEED = 0.0

TRAJECTORY = lambda t: (0, 0, 0)

DISTANCES = [0.5]
ANGLES = [0]
